/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Requerimiento1;
import modelo.Requerimiento2;
import modelo.Requerimiento3;
import static vista.VistaRequerimientosReto4.controlador;
import static vista.VistaRequerimientosReto4.requerimiento2;

/**
 *
 * @author pad
 */
public class ConstructoraGui extends javax.swing.JFrame {

    /**
     * Creates new form ConstructoraGui
     */
    public ConstructoraGui() throws SQLException {
        initComponents();
        actualizarTabla();
        actualizarTabla1();
        actualizarTabla2();
    }

    public void actualizarTabla() throws SQLException {

    ArrayList<Requerimiento1> requerimiento1 = controlador.consultarRequerimiento_1();
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

    while (modelo.getRowCount() > 0) {
        modelo.removeRow(0);
    }
    int numcols = modelo.getColumnCount();
    for (Requerimiento1 requerimiento : requerimiento1) {
        Object[] fila = new Object[numcols];

        fila[0] = requerimiento.getId_lider();
        fila[1] = requerimiento.getNombre();
        fila[2] = requerimiento.getApellido();
        fila[3] = requerimiento.getCiudad();

        modelo.addRow(fila);
    }
    
    }
    
    
    public void actualizarTabla1() throws SQLException {

    ArrayList<Requerimiento2> requerimiento2 = controlador.consultarRequerimiento_2();
    DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();

    while (modelo.getRowCount() > 0) {
        modelo.removeRow(0);
    }
    int numcols = modelo.getColumnCount();
    for (Requerimiento2 requerimiento : requerimiento2) {
        Object[] fila1 = new Object[numcols];

        fila1[0] = requerimiento.getId_compra();
        fila1[1] = requerimiento.getProveedor();
        fila1[2] = requerimiento.getConstructora();
        fila1[3] = requerimiento.getBanco_vinculado();
        fila1[4] = requerimiento.getCiudad();

        modelo.addRow(fila1);
    }
    
    }
    
    
    public void actualizarTabla2() throws SQLException {

    ArrayList<Requerimiento3> requerimiento3 = controlador.consultarRequerimiento_3();
    DefaultTableModel modelo = (DefaultTableModel) jTable3.getModel();

    while (modelo.getRowCount() > 0) {
        modelo.removeRow(0);
    }
    int numcols = modelo.getColumnCount();
    for (Requerimiento3 requerimiento : requerimiento3) {
        Object[] fila1 = new Object[numcols];

        fila1[0] = requerimiento.getId_proyecto();
        fila1[1] = requerimiento.getConstructora();
        fila1[2] = requerimiento.getHabitaciones();
        fila1[3] = requerimiento.getCiudad();
        

        modelo.addRow(fila1);
    }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTPpal = new javax.swing.JTabbedPane();
        jPReq1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPReq2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPReq3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArc = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();
        jMOpcion = new javax.swing.JMenu();
        jMRQ1 = new javax.swing.JMenuItem();
        jMRQ2 = new javax.swing.JMenuItem();
        jMRQ3 = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5");

        jPReq1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lideres");
        jPReq1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(20);
        jSplitPane1.setDividerSize(5);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Lider", "Nombre", "Apellido", "Ciudad"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        jPReq1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jTPpal.addTab("Requerimiento1", jPReq1);

        jPReq2.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Proveedor");
        jPReq2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jSplitPane2.setDividerLocation(20);
        jSplitPane2.setDividerSize(5);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jSplitPane2.setTopComponent(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Compra", "Proveedor", "Constructora", "Banco Vinculado", "Ciudad"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel4);

        jPReq2.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jTPpal.addTab("Requerimiento2", jPReq2);

        jPReq3.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Casas Campestres");
        jPReq3.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jSplitPane3.setDividerLocation(20);
        jSplitPane3.setDividerSize(5);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jSplitPane3.setTopComponent(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Proyecto", "Constructora", "Habitaciones", "Ciudad"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jPanel6.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jSplitPane3.setRightComponent(jPanel6);

        jPReq3.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        jTPpal.addTab("Requerimiento3", jPReq3);

        getContentPane().add(jTPpal, java.awt.BorderLayout.CENTER);

        jMArc.setText("File");

        jMSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMArc.add(jMSalir);

        jMenuBar1.add(jMArc);

        jMOpcion.setText("Edit");

        jMRQ1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMRQ1.setText("Requerimiento1");
        jMRQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRQ1ActionPerformed(evt);
            }
        });
        jMOpcion.add(jMRQ1);

        jMRQ2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMRQ2.setText("Requerimiento2");
        jMRQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRQ2ActionPerformed(evt);
            }
        });
        jMOpcion.add(jMRQ2);

        jMRQ3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMRQ3.setText("Requerimiento3");
        jMRQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRQ3ActionPerformed(evt);
            }
        });
        jMOpcion.add(jMRQ3);

        jMenuBar1.add(jMOpcion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMRQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRQ1ActionPerformed
         jTPpal.setSelectedIndex(0);
    }//GEN-LAST:event_jMRQ1ActionPerformed

    private void jMRQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRQ2ActionPerformed
        jTPpal.setSelectedIndex(1);
    }//GEN-LAST:event_jMRQ2ActionPerformed

    private void jMRQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRQ3ActionPerformed
        jTPpal.setSelectedIndex(2);
    }//GEN-LAST:event_jMRQ3ActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea salir ?", getTitle(), 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jMSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConstructoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConstructoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConstructoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConstructoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConstructoraGui().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ConstructoraGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMArc;
    private javax.swing.JMenu jMOpcion;
    private javax.swing.JMenuItem jMRQ1;
    private javax.swing.JMenuItem jMRQ2;
    private javax.swing.JMenuItem jMRQ3;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPReq1;
    private javax.swing.JPanel jPReq2;
    private javax.swing.JPanel jPReq3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTPpal;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
